sonar.projectKey=hub-bff
sonar.projectName=hub-bff
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
